### ISSUE TITLE
Schedule endpoint missing summer courses

### ISSUE THREAD

**Issue by SpencerMartel** [opendataConcordiaU/documentation#11]
It seems the schedule endpoint is missing courses offered in the summer semester (for summer 2022 term code 2221) for example geog 363. I think it is because it is a non standard 13 week session.

**Comment by fberrizbeitia** [comment]
I'll pass this on the SIS group. Sorry for the late response.  I'll get back to you, hopefully soon, with some answers.

**Comment by fberrizbeitia** [comment]
Hi, 

Sorry for the late response. I've been looking at the data and I couldn't find any geography offerings. I don't think is related to the length of the session as there's plenty of other courses offered during that period that appear on the results. I'm going to escalate this to the data owners. Maybe they can help us figure it out.

**Comment by opendataConcordiaU** [comment]
The data owners got back to us. With the following message:
it's fixed. should update next time the job runs. 

The data get's updated every night. Should be fine by tomorrow.

**Comment by opendataConcordiaU** [comment]
Just checked and it seems to be correct now . Closing the issue

**Comment by SpencerMartel** [comment]
Appreciate it!
