### ISSUE TITLE
Links in the documentation aren't properly formatted

### ISSUE THREAD

**Issue by volovikariel** [opendataConcordiaU/documentation#12]
Some links aren't URL-encoded and so aren't easily clickable in the documentation. For instance in the [catalog documentation](https://github.com/opendataConcordiaU/documentation/blob/master/v1/courses/catalog.md), the BIOL example doesn't work properly because the `*` symbol isn't a valid trailing URL symbol for GitHub markdown.

![image](https://user-images.githubusercontent.com/16262535/159121139-3a3a1f7a-3d27-4d2c-b9e6-88dc16199d6b.png)

The best solution I can think of is surrounding the link with opening and closing arrow brackets `<>`.

![image](https://user-images.githubusercontent.com/16262535/159121211-1cd7f8e5-9d92-41bd-b4bb-eefa20cb01c2.png)
![image](https://user-images.githubusercontent.com/16262535/159121221-05f41207-af26-44b5-8e6c-3ae2d776c171.png)

**Comment by fberrizbeitia** [comment]
Thank you very much for the feedback ... We'll fix it

**Comment by volovikariel** [comment]
#14
