### ISSUE TITLE
opendata.concordia.ca down

### ISSUE THREAD

**Issue by Neeham** [opendataConcordiaU/documentation#23]
Hello 😄!

It's day 6 and the opendata.concordia.ca site still seems to be down (affecting the APIs).

Not sure if anyone has reported it yet 😅!

Thank you!

**Comment by Tigre2325** [comment]
I was using the API first in my project, but now I switched to the raw CSV files. 
I would advise you to use them instead, especially for the course schedule as it's updated very often, and it's always accessible online without any API key.
You just need to parse them using a library or something, but imo that's worth it compared to a mon-reliable API.

Note: I am not trying to trash on the API, it's great and the documentation is good to understand the variables, but it is indeed not reliable compared to the raw CSV files.

**Comment by Neeham** [comment]
> I was using the API first in my project, but now I switched to the raw CSV files. I would advise you to use them instead, especially for the course schedule as it's updated very often, and it's always accessible online without any API key. You just need to parse them using a library or something, but imo that's worth it compared to a mon-reliable API.
> 
> _Note: I am not trying to trash on the API, it's great and the documentation is good to understand the variables, but it is indeed not reliable compared to the raw CSV files._

Aren't the raw CSV files also hosted on opendata.concordia.ca? If they are, it means they are also down unless you have downloaded a copy and are parsing that data 😅

**Comment by Tigre2325** [comment]
I read the text too fast and I thought it was only the API that was down.
I just checked, and the whole website is down, so my bad 😅
The advice still applies though once it's back up 😆

**Comment by lib-development-concordiaU** [comment]
Hi guys,

Sorry for the late response and sorry for the inconvenience. We were asked to shut down the API temporarily, I'm going to be working as of now to get it back up as  soon as possible.

**Comment by lib-development-concordiaU** [comment]
Hey Guys,

We managed to re-establish de API. Hopefully it will stay like this.

Sorry for the inconvenience.

**Comment by Neeham** [comment]
Hi @lib-development-concordiaU !

I tried calling the endpoint on my end. No success. I tried visiting http://opendata.concordia.ca still no response (ERR_CONNECTION_TIMED_OUT).

**Comment by Neeham** [comment]
Hi @lib-development-concordiaU !

It's back up and has started working again.

Looks like it got fixed sometime between `Wednesday, October 11, 2023 at 11:19:21 PM` and `Thursday, October 12, 2023 at 2:41:45 PM`

Thank you once again!
