### ISSUE TITLE
Library Opening Hours - Slim Application Error

### ISSUE THREAD

**Issue by markjamesm** [opendataConcordiaU/documentation#5]
Trying to get the [library hours](https://github.com/opendataConcordiaU/documentation/blob/master/v1/library/hours.md) API call from [https://opendata.concordia.ca/API/v1/library/hours/2020-02-16](https://opendata.concordia.ca/API/v1/library/hours/2020-02-16) results in the following Slim Application Error:

`Details 
Type: Error
Message: Call to a member function fetch_assoc() on null
File: D:\inetpub\wwwroot\opendata\Endpoints\library.php
Line: 24
`
Calls to other dates resulted in the same error.

<img width="1542" alt="Screen Shot 2020-02-16 at 11 26 38 AM" src="https://user-images.githubusercontent.com/20845425/74608457-34968500-50af-11ea-9984-1d4105093a6e.png">

**Comment by opendataConcordiaU** [comment]
This is working now. It was a connection error with one the library server ... all good now. Thank you for creatingthe issue
