### ISSUE TITLE
Upcoming Events (Library) Returns past event dates

### ISSUE THREAD

**Issue by markjamesm** [opendataConcordiaU/documentation#6]
Making a call to the [upcoming events](https://github.com/opendataConcordiaU/documentation/blob/master/v1/library/events.md) returns past events and not upcoming events.

Raw JSON response from [https://opendata.concordia.ca/API/v1/library/events/](https://opendata.concordia.ca/API/v1/library/events/) on 02/16/20:

`
{"event":[{"when":"Past Jan. 17","title":"Arduino 101","description":{},"link":{}},{"when":"Past Jan. 20","title":"Raspberry Pi 101: Cat selfie machine","description":{},"link":{}},{"when":"Past Jan. 22","title":"Arduino 101 - LOYOLA","description":{},"link":{}},{"when":"Past Jan. 23","title":"Wikipedia 101 Training - LOYOLA","description":{},"link":{}}]}
`

**Comment by opendataConcordiaU** [comment]
Thank you letting us know ... we'll look at this right away.

**Comment by opendataConcordiaU** [comment]
The issue is fixed now.
