### ISSUE TITLE
Library Hours Reporting Incorrect Values

### ISSUE THREAD

**Issue by markjamesm** [opendataConcordiaU/documentation#7]
I just noticed that some of the hours returned from the [library hours](https://github.com/opendataConcordiaU/documentation/blob/master/v1/library/hours.md) call are incorrect. For example, both Webster and Vanier Libraries are listed as open from 10PM to 10PM. 

![Screen Shot 2020-02-17 at 10 58 13 PM](https://user-images.githubusercontent.com/20845425/74702759-fb5a3400-51d8-11ea-8482-c47ccaa50990.png)

The call in question: 

https://opendata.concordia.ca/API/v1/library/hours/2020-02-17

**Comment by markjamesm** [comment]
Could this be happening because both libraries are 24h?

**Comment by opendataConcordiaU** [comment]
Hi Marc,

Yes, you're correct,  that's why is returning the same value for both, start time and end time.  We added a little logic on the website and the digital signage to display it better. 

I hope this helps,

Francisco
