### ISSUE TITLE
Enable CORS?

### ISSUE THREAD

**Issue by huntertran** [opendataConcordiaU/documentation#9]
I'm getting CORS error when consuming the API from my site

> Access to fetch at 'https://opendata.concordia.ca/API/v1/facilities/buildinglist/' from origin 'https://my_site' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by usamasaleem1** [comment]
Same here. Any luck?
